services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  db:
    image: mongo:7.0.5-rc0-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - simpleoj:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  server:
    build: ./server
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb+srv://codenex:test123@codenex.moq78oe.mongodb.net/?retryWrites=true&w=majority&appName=codenex

    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - redis
      - db
    depends_on:
      - db

  redis:
    image: redis:7.2.3-alpine

volumes:
  simpleoj:
